import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";

export const metadata = {
  title: "Study Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <ThemeProvider>
          <Navbar />
          <main className="main">
            <section className="main-section">{children}</section>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
