import Navbar from "@/components/navbar/Navbar";
import "./globals.css";

export const metadata = {
  title: "Study Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Navbar />
        <main className="main">
          <section className="main-section">{children}</section>
        </main>
      </body>
    </html>
  );
}
